# Generated by Django 5.1.4 on 2025-02-08 08:42

import django.utils.timezone
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
