# Generated by Django 5.1.4 on 2025-02-08 12:21

import catalog.validators
import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos', validators=[catalog.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'png'], 'Расширение файла « %(extension)s » не допускается. Разрешенные расширения: %(allowed_extensions)s .Недопустимое расширение!')], verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=150, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Изображение'),
        ),
    ]
