# Generated by Django 5.1.4 on 2025-02-09 14:49

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=150, verbose_name='Страна'),
        ),
    ]
