# Generated by Django 5.1.4 on 2025-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(default='Здесь пока ничего нет.', verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='Превью')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('number_views', models.IntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['create_at'],
            },
        ),
    ]
