# Generated by Django 5.1.4 on 2025-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogarticle_number_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='number_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
