# Generated by Django 5.1.4 on 2025-02-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'ordering': ['create_at'], 'permissions': [('can_publish_blogarticle', 'Публикация статьи блога')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
