# Generated by Django 5.1.4 on 2024-12-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('mailing_address', models.TextField(blank=True, null=True, verbose_name='Почтовый адрес')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['updated_at', 'name_p'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
