# Generated by Django 5.1.4 on 2024-12-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contact_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_p',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
