# Generated by Django 5.1.4 on 2024-12-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_name_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images', verbose_name='Изображение'),
        ),
    ]
