# Generated by Django 5.1.4 on 2025-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit_sales',
            field=models.BooleanField(default=False, verbose_name='Хит продаж!'),
        ),
    ]
