# Generated by Django 5.1.4 on 2025-01-14 18:20

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_by',
            field=models.IntegerField(validators=[catalog.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpeg', 'png'], 'Расширение файла « %(extension)s » не допускается. Разрешенные расширения: %(allowed_extensions)s .', 'Недопустимое расширение!')], verbose_name='Цена за покупку'),
        ),
    ]
