# Generated by Django 5.1.4 on 2025-01-14 19:12

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_picture_alter_product_price_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images', validators=[catalog.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'png'], 'Расширение файла « %(extension)s » не допускается. Разрешенные расширения: %(allowed_extensions)s .', 'Недопустимое расширение!')], verbose_name='Изображение'),
        ),
    ]
